### ISSUE TITLE
Links to subtasks on top-level README are broken

### ISSUE THREAD

**Issue by joshstephenson** [sigmorphon/2024TokenST#1]
Subtask 1: [Word and Definition](https://github.com/sigmorphon/2024TokenST#)
Subtask 2: [Word and Word](https://github.com/sigmorphon/2024TokenST#)
Subtask 3: [Word and Morphology](https://github.com/sigmorphon/2024TokenST#)
Subtask 4: [Machine Translation](https://github.com/sigmorphon/2024TokenST#)

The above links are broken. Apologies if this is still a work in progress, but I'd love to read about those subtasks.

Links to "Stay up to date" are also broken.

**Comment by kbatsuren** [comment]
Hi @joshstephenson,

We are sorry for the late start. We will release all the details and datasets this week.

**Comment by kbatsuren** [comment]
Hi @joshstephenson,

We have just released the datasets.

**Comment by kbatsuren** [comment]
I am closing this issue.
