### ISSUE TITLE
WaD dev data has no labels

### ISSUE THREAD

**Issue by bpopeters** [sigmorphon/2024TokenST#2]
Hi, the labels are missing from the WaD dev set. Will they be released soon?

**Comment by kbatsuren** [comment]
Hi @bpopeters,

I am sorry that I haven't seen it. WaD dev split has the label column. Am I missing something here?

**Comment by bpopeters** [comment]
data/WaD.dev.tsv does not have labels, at least not on the main branch.

**Comment by zouharvi** [comment]
Hi Ben, the labels seem to be in the last column. In the tsv preview, you have to scroll to the right. Could you please elaborate on the problem?

```
$ data = open("WaD.dev.tsv", "r").readlines()
$ data = [x.strip().split("\t") for x in data]
$ data[0]
['index', 'word', 'definition', 'label']
$ data[1]
['0', 'brass', 'a surgical procedure in which tissue or whole organs are transfered from one species to another species', '0']
$ data[5]
['4', 'forget', 'a medical procedure involving an incision with instruments; performed to repair damage or arrest disease in a living body', '0']
```

![image](https://github.com/sigmorphon/2024TokenST/assets/7661193/87c064fa-0608-4a2b-89c3-b13375a25541)

![image](https://github.com/sigmorphon/2024TokenST/assets/7661193/7424ad02-8d81-446e-a9df-df65febe7a82)

**Comment by bpopeters** [comment]
Whoopsadaisie, I see them now.

**Comment by zouharvi** [comment]
No worries. :slightly_smiling_face:
